$packageName = "{{PackageName}}"
$url = "{{DownloadUrl}}"
$url64 = "{{DownloadUrlx64}}"
$unzipLoc = "$(Split-Path -parent $MyInvocation.MyCommand.Definition)"
Install-ChocolateyZipPackage -PackageName "$packageName" -Url "$url" -UnzipLocation "$unzipLoc" -Url64bit "$url64"